# Change these first
owner: amcohrs-oradoo # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: Pro Putt Systems
    url: https://proputtsystems.com
  - name: Carolina Custom Putting Greens
    url: https://www.carolinacustomputtinggreens.com
  - name: Pro Backyard
    url: https://www.outdoortvpros.com
  - name: Turf Innovations
    url: https://www.turfinnovations.com
  - name: Loyal Toys
    url: https://loyaltoys.com
  - name: Pro Court Systems
    url: https://procourtsystems.com
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.oradoo.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Oradoo Uptime Status
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
